title: "Mission International"
author: davidschirduan
email: davidschirduan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bringing hope and changing lives through the good news of the Gospel.

baseurl:

twitter_username: 
github_username:  

sass:
    style: compressed