title: Mission International
author: davidschirduan
email: davidschirduan@gmail.com
description: 'Bringing hope and changing lives through the good news of the Gospel.'

baseurl: '/'
url: 'https://mission-international.net'
google_analytics: 'UA-49566007-1'
twitter_username: 
github_username:  

sass:
    style: compressed


